export { default as Home } from './Home';
export { default as Portfolio } from './Portfolio';
export { default as About } from './About';
export { default as Skills } from './Skills';
export { default as Experience } from './Experience';
export { default as Projects } from './Projects';
export { default as ProjectDetail } from './ProjectDetail';
export { default as Education } from './Education';
export { default as Resume } from './Resume';
export { default as Contact } from './Contact';
export { default as NotFound } from './NotFound';
export * from './admin';
